import json

def lambda_handler(event, context):
    # HTML content as a string
    html_content = """
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>My Lambda Frontend</title>
        <style>
            body {
                font-family: Arial, sans-serif;
                background-color: #f4f4f4;
                margin: 0;
                padding: 0;
            }
            header {
                background-color: #333;
                color: white;
                text-align: center;
                padding: 10px;
            }
            main {
                padding: 20px;
            }
            button {
                background-color: #4CAF50;
                color: white;
                padding: 10px 20px;
                border: none;
                cursor: pointer;
                font-size: 16px;
            }
            button:hover {
                background-color: #45a049;
            }
        </style>
    </head>
    <body>
        <header>
            <h1>Welcome to My Lambda Frontend Page!</h1>
        </header>
        <main>
            <p>This page is generated by an AWS Lambda function.</p>
            <button onclick="alert('Hello from Lambda!')">Click Me</button>
        </main>
    </body>
    </html>
    """
    
    # Return the HTML content as the body of the response
    return {
        'statusCode': 200,
        'headers': {
            'Content-Type': 'text/html'
        },
        'body': html_content
    }
